codecov:
  bot: "codecov-io"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: false
  require_ci_to_pass: true
  notify:
    after_n_builds: 2
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "50...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true