# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@1.2.3
    
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
    # Checkout the code as the first step.
    - checkout
    - run:
          name: Build
          command: mvn -B -DskipTests

  test-and-coverage:
    docker:
      - image: cimg/openjdk:11.0
    steps:
    - run:
          name: Test
          command: mvn test
    - store_artifacts:
          path: target
    - codecov/upload:
          file: target/jacoco.exec

  clean:
    docker:
      - image: cimg/openjdk:11.0
    steps:
    - run:
          name: Clean
          command: mvn clean package
    
          
workflows:
  sample:
    jobs:
      - build
      - test-and-coverage
      - clean